export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import toast, { Toaster } from 'react-hot-toast';
import StoreProvider from "@/components/StoreProvider";
import Sidebar from "@/components/Sidebar";
// import { ST } from 'next/dist/shared/lib/utils';


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
<div className="grid grid-cols-5">
<div className="col-span-1 ">
<Sidebar/>
</div>
<div className="col-span-4">
    <Toaster />
  {children}
</div>
</div>
    
        </StoreProvider>
      </body>
    </html>
  )
}