"use client"
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }
import { useState } from 'react';
import toast, { Toaster } from 'react-hot-toast';
import StoreProvider from "@/components/StoreProvider";
import Sidebar from "@/components/Sidebar";
import Header from '@/components/Header';
import RouteLoaderWrapper from "@/components/RouteLoaderWrapper";
// import { ST } from 'next/dist/shared/lib/utils';


export default function RootLayout({ children }) {
  const [activeTab, setActiveTab] = useState("dashboard");
  return (
    <html lang="en">
      <body>
        <RouteLoaderWrapper>
        <StoreProvider>
<div className="md:grid md:grid-cols-5">
<div className="col-span-1 ">
 <Sidebar activeTab={activeTab} setActiveTab={setActiveTab} />
</div>

<div className="col-span-4">
  <Header/>
    <Toaster />
  {children}
</div>
</div>
    
        </StoreProvider>
         </RouteLoaderWrapper>
      </body>
    </html>
  )
}