export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import StoreProvider from "@/components/StoreProvider";
import  { Toaster } from 'react-hot-toast';
// import { ST } from 'next/dist/shared/lib/utils';


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>

          {/* <ToastContainer position="bottom-right"/> */}
          {children}
          <Toaster />
        </StoreProvider>
      </body>
    </html>
  )
}