import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/components/StoreProvider";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "IndianLudoking Admin Panel",
  description: "Generated by create next app",
icons: "/images/image.png",          // default favicon
    shortcut: "/images/image.png",      // for legacy browsers
    apple: "/images/image.png",    
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={` `}
      >
      {children}
      </body>
    </html>
  );
}
//ok done.  
























